# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 19:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('livingExpense', models.PositiveIntegerField()),
                ('minTemperature', models.FloatField(validators=[django.core.validators.MaxValueValidator(212)])),
                ('maxTemperature', models.FloatField(validators=[django.core.validators.MaxValueValidator(212)])),
                ('logo', models.FileField(blank=True, default=None, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
                ('courseDescription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=50)),
                ('rank', models.PositiveIntegerField()),
                ('acceptedGRE', models.PositiveIntegerField(blank=True, null=True, validators=[
                    django.core.validators.MaxValueValidator(340)])),
                ('acceptedGMAT', models.PositiveIntegerField(blank=True, null=True, validators=[
                    django.core.validators.MaxValueValidator(800)])),
                ('acceptedTOEFL',
                 models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(120)])),
                ('minCGPA', models.FloatField(blank=True, null=True)),
                ('feePerCredit', models.PositiveIntegerField()),
                ('avgWorkExp',
                 models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sFirstName', models.CharField(max_length=50)),
                ('sLastName', models.CharField(max_length=100)),
                ('sDateOfBirth', models.DateField()),
                ('sPhoneNumber', models.PositiveIntegerField()),
                ('sEmailId', models.EmailField(max_length=254)),
                ('sGRE', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(340)])),
                ('sGMAT', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(800)])),
                ('sCGPA', models.FloatField()),
                ('sWorkExp', models.FloatField(validators=[django.core.validators.MaxValueValidator(100.0)])),
                ('sUnderGradSteam', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('logo', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.City')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.AddField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.University'),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.University'),
        ),
    ]
