# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='livingExpense',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='maxTemperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='minTemperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
