# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('rankings', '0002_auto_20171123_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
    ]
