# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rankings', '0003_auto_20171123_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AddField(
            model_name='university',
            name='isFavourite',
            field=models.BooleanField(default=False),
        ),
    ]
