# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rankings', '0004_auto_20171124_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
