# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-27 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rankings', '0005_auto_20171126_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='logo',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
